fix logic error introduced by lint fixes

diff --git a/cc-ansible b/cc-ansible
--- a/cc-ansible
+++ b/cc-ansible
@@ -224,9 +224,9 @@ if [[ "$CHECK_UPDATES" == "yes" || "$FORCE_UPDATES" == "yes" ]]; then
         ! diff -q >/dev/null \
           "$kolla_ansible_gitref" \
           <(cd "$kolla_ansible_egglink"; git fetch; git show-ref -s -d origin/"$kolla_ansible_checkout"); then
-    pushd "$VIRTUALENV" || echo "pushd error!" && exit 1
+    pushd "$VIRTUALENV" || ( echo "pushd error!" && exit 1 )
     pip install -e git+"$kolla_ansible_remote"@"$kolla_ansible_checkout"#egg=kolla-ansible
-    popd || echo "popd error!" && exit 1
+    popd || ( echo "popd error!" && exit 1 )
     # [jca 2020-01-30] TODO:
     # Ensure the /share folder is placed; this is not copied when using the "develop" setup.py method.
     # This is a bit weird, perhaps there is some way to pass an additional flag to pip to make it
