refactor venv creation and updates
Refactor installation steps into functions for ease of maintenance.
Splits the monolithic installation into separate steps for:
- virtualenv
- python requirements
- ansible galaxy roles and collections
- installing kolla-ansible from git
- installing misc tools like `yq`

During setup, the venv is added to the path, so we do not need
to reference it explicitly in later commands.

diff --git a/cc-ansible b/cc-ansible
--- a/cc-ansible
+++ b/cc-ansible
@@ -5,29 +5,122 @@ set -o nounset
 set -o pipefail
 # set -o xtrace
 
-DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
-VIRTUALENV="$(realpath "${VIRTUALENV:-"${DIR}"/venv}")"
-
+# Set Globals
 FORCE_UPDATES="${FORCE_UPDATES:-no}"
-if [[ ! -d ${VIRTUALENV} ]]; then
-	echo "Creating virtualenv at ${VIRTUALENV} ..."
-	python3 -m venv "${VIRTUALENV}" --system-site-packages
-	"${VIRTUALENV}/bin/pip" install --upgrade pip
-	FORCE_UPDATES=yes
-fi
-
-set +o nounset
-# shellcheck disable=1090 # TODO use standard VIRTUAL_ENV and PATH method
-source "$(realpath ${VIRTUALENV}/bin/activate)"
-set -o nounset
-
 CHECK_UPDATES=yes
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
+
+setup_venv() {
+	local venv_path="${VIRTUAL_ENV:-"${DIR}"/"venv"}"
+	VIRTUAL_ENV=$(realpath "${venv_path}")
+
+	if [[ ! -d ${VIRTUAL_ENV} ]]; then
+		echo "Creating virtualenv at ${VIRTUAL_ENV} ..."
+		python3 -m venv "${VIRTUAL_ENV}"
+	fi
+
+	# Set venv paths for later commands
+	export VIRTUAL_ENV
+	export VIRTUAL_ENV="${VIRTUAL_ENV}"
+	export PATH="${VIRTUAL_ENV}/bin:${PATH}"
+
+	# Ensure latest version of pip
+	pip install --upgrade pip
+}
+
+update_python_packages() {
+	# Update base pip packages
+	pip_requirements="${DIR}/requirements.txt"
+	pip_requirements_chksum="${VIRTUAL_ENV}/requirements.txt.sha256"
+	if [[ ${FORCE_UPDATES} == "yes" || ! -f ${pip_requirements_chksum} ]] ||
+		! sha256sum --quiet --check "${pip_requirements_chksum}"; then
+		pip install --upgrade --force-reinstall -r "${pip_requirements}"
+		sha256sum "${pip_requirements}" >"${pip_requirements_chksum}"
+	fi
+}
+
+update_ansible_galaxy() {
+	# Update Ansible Galaxy roles
+	galaxy_role_path="${DIR}/roles/galaxy.ansible.com"
+	galaxy_role_requirements="${DIR}/requirements.yml"
+	galaxy_role_requirements_chksum="${VIRTUAL_ENV}/requirements.yml.sha256"
+	if [[ ${FORCE_UPDATES} == "yes" || ! -f ${galaxy_role_requirements_chksum} ]] ||
+		! sha256sum --quiet --check "${galaxy_role_requirements_chksum}"; then
+		ansible-galaxy role install --force -p "${galaxy_role_path}" -r "${galaxy_role_requirements}"
+		sha256sum "${galaxy_role_requirements}" >"${galaxy_role_requirements_chksum}"
+	fi
+
+}
+
+update_kolla_ansible() {
+	local kolla_ansible_remote=https://github.com/ChameleonCloud/kolla-ansible.git
+	local kolla_ansible_checkout="${KOLLA_ANSIBLE_BRANCH:-chameleoncloud/xena}"
+	local kolla_ansible_gitref="${VIRTUAL_ENV}/kolla-ansible.gitref"
+	local kolla_ansible_egglink="${VIRTUAL_ENV}/src/kolla-ansible"
+
+	detect_gitref_change() {
+		set -x
+
+		pushd "${kolla_ansible_egglink}"
+		git fetch
+		current_kolla_ansible_gitref_value=$(git show-ref -s -d origin/"${kolla_ansible_checkout}")
+		popd
+
+		kolla_ansible_gitref_value=$(cat "${kolla_ansible_gitref}")
+
+		if [[ ${kolla_ansible_gitref_value} == "${current_kolla_ansible_gitref_value}" ]]; then
+			return 0
+		else
+			return 1
+		fi
+
+		set +x
+	}
+
+	gitref_changed=detect_gitref_change
+
+	if [[ ${FORCE_UPDATES} == "yes" || ! -f ${kolla_ansible_gitref} || ! -d ${kolla_ansible_egglink} || -z ${gitref_changed} ]]; then
+		pushd "${VIRTUAL_ENV}" || (echo "pushd error!" && exit 1)
+		python3 -m pip install -e "git+${kolla_ansible_remote}@${kolla_ansible_checkout}#egg=kolla-ansible"
+		popd || (echo "popd error!" && exit 1)
+		# [jca 2020-01-30] TODO:
+		# Ensure the /share folder is placed; this is not copied when using the "develop" setup.py method.
+		# This is a bit weird, perhaps there is some way to pass an additional flag to pip to make it
+		# copy this even though it's installing as source. We use source install to keep track of the Git revision.
+		mkdir -p "${VIRTUAL_ENV}/share" && ln -sf "${kolla_ansible_egglink}" "${VIRTUAL_ENV}/share/kolla-ansible"
+		(
+			cd "${kolla_ansible_egglink}"
+			git rev-parse HEAD >"${kolla_ansible_gitref}"
+		)
+	fi
+}
+
+update_yq() {
+	# Update/install yq
+	YQ_VERSION=4.9.6
+	if [[ "$(type -t yq)" != "file" ]]; then
+		YQ_BINARY="yq_linux_amd64"
+		wget https://github.com/mikefarah/yq/releases/download/v"${YQ_VERSION}"/"${YQ_BINARY}".tar.gz -O - |
+			tar xz && mv "${YQ_BINARY}" "${VIRTUAL_ENV}/bin/yq"
+	fi
+
+}
+
 declare -a POSARGS=()
 declare -a TRAPS=()
 cleanup() {
 	for exit_trap in "${TRAPS[@]}"; do "${exit_trap}"; done
 }
 trap cleanup EXIT
+
+setup_venv
+# Automatically update dependencies
+if [[ ${CHECK_UPDATES} == "yes" || ${FORCE_UPDATES} == "yes" ]]; then
+	echo "Updating Python Packages" && update_python_packages
+	echo "Updating Ansible Galaxy Roles" && update_ansible_galaxy
+	echo "Updating Kolla Ansible from Git" && update_kolla_ansible
+	echo "Updating YQ Tool" && update_yq
+fi
 
 while [[ $# -gt 0 ]]; do
 	key="$1"
@@ -213,64 +306,7 @@ if [[ -f ${CC_ANSIBLE_ENV} ]]; then
 	set +a
 fi
 
-# Automatically update dependencies
-if [[ ${CHECK_UPDATES} == "yes" || ${FORCE_UPDATES} == "yes" ]]; then
-	# Update base pip packages
-	pip_requirements="${DIR}/requirements.txt"
-	pip_requirements_chksum="${VIRTUALENV}/requirements.txt.sha256"
-	if [[ ${FORCE_UPDATES} == "yes" || ! -f ${pip_requirements_chksum} ]] ||
-		! sha256sum --quiet --check "${pip_requirements_chksum}"; then
-		pip install --upgrade --force-reinstall -r "${pip_requirements}"
-		sha256sum "${pip_requirements}" >"${pip_requirements_chksum}"
-	fi
-
-	# Update Ansible Galaxy roles
-	galaxy_role_path="${DIR}/roles/galaxy.ansible.com"
-	galaxy_role_requirements="${DIR}/requirements.yml"
-	galaxy_role_requirements_chksum="${VIRTUALENV}/requirements.yml.sha256"
-	if [[ ${FORCE_UPDATES} == "yes" || ! -f ${galaxy_role_requirements_chksum} ]] ||
-		! sha256sum --quiet --check "${galaxy_role_requirements_chksum}"; then
-		ansible-galaxy role install --force -p "${galaxy_role_path}" -r "${galaxy_role_requirements}"
-		sha256sum "${galaxy_role_requirements}" >"${galaxy_role_requirements_chksum}"
-	fi
-
-	kolla_ansible_remote=https://github.com/chameleoncloud/kolla-ansible.git
-	kolla_ansible_checkout=${KOLLA_ANSIBLE_BRANCH:-chameleoncloud/xena}
-	kolla_ansible_gitref="${VIRTUALENV}/kolla-ansible.gitref"
-	kolla_ansible_egglink="${VIRTUALENV}/src/kolla-ansible"
-	if [[ ${FORCE_UPDATES} == "yes" || ! -f ${kolla_ansible_gitref} || ! -d ${kolla_ansible_egglink} ]] ||
-		! diff -q \
-			"${kolla_ansible_gitref}" \
-			<(
-				cd "${kolla_ansible_egglink}"
-				git fetch
-				git show-ref -s -d origin/"${kolla_ansible_checkout}"
-			) >/dev/null \
-		; then
-		pushd "${VIRTUALENV}" || (echo "pushd error!" && exit 1)
-		pip install -e git+"${kolla_ansible_remote}"@"${kolla_ansible_checkout}#egg=kolla-ansible"
-		popd || (echo "popd error!" && exit 1)
-		# [jca 2020-01-30] TODO:
-		# Ensure the /share folder is placed; this is not copied when using the "develop" setup.py method.
-		# This is a bit weird, perhaps there is some way to pass an additional flag to pip to make it
-		# copy this even though it's installing as source. We use source install to keep track of the Git revision.
-		mkdir -p "${VIRTUALENV}/share" && ln -sf "${kolla_ansible_egglink}" "${VIRTUALENV}/share/kolla-ansible"
-		(
-			cd "${kolla_ansible_egglink}"
-			git rev-parse HEAD >"${kolla_ansible_gitref}"
-		)
-	fi
-
-	# Update/install yq
-	YQ_VERSION=4.9.6
-	if [[ "$(type -t yq)" != "file" ]]; then
-		YQ_BINARY="yq_linux_amd64"
-		wget https://github.com/mikefarah/yq/releases/download/v"${YQ_VERSION}"/"${YQ_BINARY}".tar.gz -O - |
-			tar xz && mv "${YQ_BINARY}" "${VIRTUALENV}/bin/yq"
-	fi
-fi
-
-ansible_path="${VIRTUALENV}/share/kolla-ansible/ansible"
+ansible_path="${VIRTUAL_ENV}/share/kolla-ansible/ansible"
 
 # Handle subcommands
 if [[ -n ${command:-} ]]; then
@@ -364,7 +400,8 @@ kolla_args+=(--extra site_config_dir="${CC_ANSIBLE_SITE}")
 
 # We set ansible ansible_python_interpreter to the virtualenv inside site-config, and override here during bootstrap.
 # Overriding at the CLI here applies to all hosts, including the deploy host.
-# Bootstrap-servers creates a virtualenv at ${VIRTUALENV}, on all hosts except the deploy host, requiring a special case.
+# Bootstrap-servers creates a virtualenv at the path stored in the ansible variable {{ virtualenv }},
+# on all hosts except the deploy host, requiring a special case.
 # The old behavior was to set it here if NOT bootstrapping, but that fails for the deploy-host case.
 
 if [[ ${POSARGS[*]} =~ bootstrap-servers ]]; then
@@ -386,5 +423,4 @@ if [[ -n ${ANSIBLE_SKIP_TAGS} ]]; then
 	kolla_args+=("${ANSIBLE_SKIP_TAGS}")
 fi
 
-"${VIRTUALENV}"/bin/kolla-ansible "${kolla_args[@]}"
-# set +o xtrace
+kolla-ansible "${kolla_args[@]}"
