Prevent accidental overwrite of passwords.yml
If the wrong key is provided, there are conditions where the passwords.yml
file can be overwritten. This adds guards for that; it checks that the
file was decrypted properly, and additionally adds a check for 0 changes after
editing (to prevent re-encryption and changing contents, which can be annoying
if the file is under VCS.)

diff --git a/cc-ansible b/cc-ansible
--- a/cc-ansible
+++ b/cc-ansible
@@ -100,10 +100,13 @@ init() {
 
 edit_passwords() {
   local tmpfile
+  local passwords_file="$CC_ANSIBLE_SITE/passwords.yml"
+  local passwords_file_chksum="${passwords_file}.sha256"
 
   tmpfile="$(mktemp)"
   _edit_passwords_cleanup() {
     rm -f "$tmpfile"
+    rm -f "$passwords_file_chksum"
   }
   TRAPS+=(_edit_passwords_cleanup)
 
@@ -111,9 +114,21 @@ edit_passwords() {
   ansible-vault view \
     --vault-password-file "$CC_ANSIBLE_VAULT_PASSWORD" \
     "$CC_ANSIBLE_SITE/passwords.yml" >"$tmpfile"
+
+  if [[ ! -s "$tmpfile" ]]; then
+    echo "Failed to decrypt $passwords_file with vault token."
+    exit 1
+  fi
+
+  sha256sum "$tmpfile" >"$passwords_file_chksum"
   ${EDITOR:-vi} "$tmpfile"
   local ret=$?
   if [[ $ret -gt 0 ]]; then exit $ret; fi
+  if [[ sha256sum --quiet --check "$passwords_file_chksum" ]]; then
+    echo "No passwords were changed."
+    exit 0
+  fi
+
   echo "Generating placeholder passwords for any missing values..."
   kolla-genpwd --passwords "$tmpfile"
   echo "Encrypting passwords..."
